name: manage-azure-policy-92ed06d5
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/EK-Deploy_Diagnostic_settings_(Logs)_for_PaaS_Services_32f82781-705e-4a1c-838b-a3a36fdc5f33/**'
#      - 'initiatives/EK-ResourceNamingStandard_fdf1172e-e8ed-491d-a529-173aef9b200f/**'
#      - .github/workflows/manage-azure-policy-92ed06d5.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_92ed06d5}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          initiatives/EK-Deploy_Diagnostic_settings_(Logs)_for_PaaS_Services_32f82781-705e-4a1c-838b-a3a36fdc5f33/**
          initiatives/EK-ResourceNamingStandard_fdf1172e-e8ed-491d-a529-173aef9b200f/**
